### ISSUE TITLE
Bug with isFuture flag

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/heatmap#21]
Current day tile is incorrectly marked as "future one".

Te replicate:

```php
        $builder = new HeatmapBuilder(
            periodInterval: PeriodInterval::Weekly,
            period: new CarbonPeriod($firstEpisode->watched_at, "1 week", Carbon::now()->endOfYear()),
            arrayAccessIndex: "watched_at",
            decorator: new Decorator("sky"),
            alignedToEndOfPeriod: true,
        );
```

Screenshot:
![image](https://github.com/blumilksoftware/heatmap/assets/10898728/ffcef566-13ee-4446-bf5b-7d99e129e09d)

Current week's tile receives `$futureTileClass` in tile's decorator.  It should not.

**Comment by BarTracz** [comment]
This is pretty weird behavior, because for me this bug only happens when period is from lets say June 1 and date is set to last week of June, but when i set May or any other month that is before as period start it works fine.
![nieok1](https://github.com/blumilksoftware/heatmap/assets/115506125/7394f9b2-9620-4503-a2fd-7490fc05257f)
![ok1](https://github.com/blumilksoftware/heatmap/assets/115506125/b92bbb9c-05db-4e3c-a945-60336ed40fa6)

**Comment by BarTracz** [comment]
Could this be a Carbon bug? `inFuture: $date->isFuture()` is responsible for checking if date is in future and then decorator gives  tile opacity to mark it as future tile, so i don`t see any other way that could be broken.

**Comment by BarTracz** [comment]
![hm](https://github.com/blumilksoftware/heatmap/assets/115506125/cb518a3c-caa2-422b-b5a7-8060f597fba7)
Current week is marked both as current and future
